
production:
  adapter: mysql
  encoding: utf8
  database: wipeitout_production
  username: wipeitout_db
  password: 0ut1tw1p3
  host: mysql.wipeitout.com.au
  
development:
  adapter: mysql
  database: wipeitout_dev
  username: wipeitout_dev
  password: wipeitout_dev
  host: localhost

